# Generated by Django 5.0.4 on 2024-05-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developquiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='score',
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.CharField(default=False, max_length=225, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct'),
        ),
    ]
